dhis2/data-quality-app

src/components/available-datasets-select/AvailableDatasetsSelect.js, src/components/download-as/DownloadAs.css, src/components/download-as/DownloadAs.js, src/components/outlier-analysis-table/OutlierAnalysisTable.js, src/helpers/dates.js, src/i18n.js, src/pages/Page.js, src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js, src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js, src/server.conf.js
Missing feedback snackbar yet;
Needed server side endpoints [here](https://github.com/joaoantunes87/dhis2-core/tree/data-quality-app);
=> Outlier analysis

src/components/datasets-for-organisation-unit-select/DatasetsForOrganisationUnitSelect.js, src/components/outlier-analysis-table/OutlierAnalysisTable.js, src/i18n.js, src/pages/follow-up-analysis/FollowUpAnalysis.js, src/pages/follow-up-analysis/follow-up-analysis-table/FollowUpAnalysisTable.js, src/server.conf.js
Missing feedback snackbar yet;
Needed server side endpoints [here](https://github.com/joaoantunes87/dhis2-core/tree/data-quality-app);
=> Followup analysis

e2e/features/help.feature, e2e/features/home.feature, e2e/features/sideMenu.feature, e2e/features/validationRuleAnalysis.feature, e2e/features/validationRuleAnalysisResult.feature
The first version of feature files for help, menu, home and validation rule analysis
=> Created feature files

e2e/features/followUpAnalysis.feature, e2e/features/followUpRuleAnalysisResult.feature, e2e/features/minMaxOutlierAnalysis.feature, e2e/features/stdDevOutlierAnalysis.feature
Contains the feature files for Follow Up, Min-Max Outlier, STD Dev Outlier Analysis
=> Files for Analysis sections

src/index.js
https://jira.dhis2.org/browse/DHIS2-10246
=> fix: unregister service worker

src/index.js
https://jira.dhis2.org/browse/DHIS2-10246
=> fix: unregister service worker (v35)

src/index.js
https://jira.dhis2.org/browse/DHIS2-10246
=> fix: unregister service worker (v33)

src/index.js
https://jira.dhis2.org/browse/DHIS2-10246
=> fix: unregister service worker (v34)

i18n/en.pot, src/App.js, src/pages/home/grid-section/GridSection.js, src/pages/sections.conf.js
It turned out we were still using some static strings
=> fix(sections): fix missing translations

i18n/en.pot, src/App.js, src/pages/home/grid-section/GridSection.js, src/pages/sections.conf.js
Some context info here: https://github.com/dhis2/data-quality-app/pull/680#issue-565177484
=> fix(sections): fix missing translations (v34)

i18n/en.pot, src/App.module.css, src/components/outlier-analysis-table/OutlierAnalysisTable.js, src/components/outlier-analysis-table/OutlierAnalysisTable.test.js, src/pages/outlier-detection/OutlierDetection.js, src/pages/outlier-detection/OutlierDetection.test.js, src/server.conf.js
There was [some discussion](https://dhis2.slack.com/archives/CPGUFVC56/p1611823840051400) going on about how the new `followup/dataValues` endpoint should be implemented. The webapi has been updated now and I've adjusted the client code. So this should be ready to get merged in.
See relevant API docs here: https://docs.dhis2.org/master/en/dhis2_developer_manual/web-api.html#follow-up
=> feat(outlier-detection): mark data values for follow-up (DHIS2-10339)

src/helpers/threeMonthsAgo.js, src/pages/follow-up-analysis/FollowUpAnalysis.js, src/pages/outlier-detection/OutlierDetection.js, src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
No JIRA issue available, this was a requested by Lars.
=> feat: set start date to three months ago in all sections

src/helpers/threeMonthsAgo.js, src/pages/follow-up-analysis/FollowUpAnalysis.js, src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js, src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js, src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
No JIRA issue available, this was a requested by Lars.
=> feat: set start date to three months ago in all sections (v35)

d2.config.js, package.json, yarn.lock
Related to [DHIS2-9893](https://jira.dhis2.org/browse/DHIS2-9893)
=> feat: upgrade to @dhis2/ui v6 and bump other dependency versions

src/pages/outlier-detection/Form.js, src/pages/outlier-detection/OutlierDetection.js, src/pages/outlier-detection/constants.js
I was using the wrong queryParam name (`sortBy` instead of `orderBy`) and the wrong default value (`Z_SCORE` instead of `MEAN_ABS_DEV`).
=> fix(outlier-detection): change sortBy to orderBy and default value

src/pages/outlier-detection/Form.js, src/pages/outlier-detection/OutlierDetection.js, src/pages/outlier-detection/constants.js
=> fix(outlier-detection): change sortBy to orderBy and default value (patch/2.36.0)

package.json, yarn.lock
https://github.com/dhis2/data-quality-app/pull/721
=> fix: update @dhis2/ui to 6.5.6 due to fixed select filter z-index (v36)

package.json, yarn.lock
https://github.com/dhis2/data-quality-app/pull/721
=> fix: update @dhis2/ui to 6.5.6 due to fixed select filter z-index (2.36.0) [DHIS2-10731]

src/components/available-organisation-units-tree/AvailableOrganisationUnitsTree.js
=> fix(org-unit-tree): load user org-units (2.36.0)

src/components/available-organisation-units-tree/AvailableOrganisationUnitsTree.js
=> fix(org-unit-tree): load user org-units (v36)

src/pages/outlier-detection/Form.js, src/pages/outlier-detection/Form.module.css, src/pages/outlier-detection/OutlierDetection.js, src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
v36 backport of https://github.com/dhis2/data-quality-app/pull/745
=> fix: update end dates for visualisation analysis and outliers (v36)

i18n/en.pot, src/pages/follow-up-analysis/FollowUpAnalysis.js, src/pages/outlier-detection/OutlierDetection.js, src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
v36 backport of https://github.com/dhis2/data-quality-app/pull/748
=> fix: preserve org-unit state when navigating back from table (v36)

src/pages/outlier-detection/Form.js, src/pages/outlier-detection/Form.module.css, src/pages/outlier-detection/OutlierDetection.js, src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
2.36.0 backport of https://github.com/dhis2/data-quality-app/pull/745
=> fix: update end dates for visualisation analysis and outliers (2.36.0)

src/components/page-helper/PageHelper.js, src/helpers/docs.js, src/pages/outlier-detection/OutlierDetection.js
Closes https://jira.dhis2.org/browse/DHIS2-11230
=> fix: update documentation URLs 

src/components/page-helper/PageHelper.js, src/helpers/docs.js, src/pages/outlier-detection/OutlierDetection.js
Closes https://jira.dhis2.org/browse/DHIS2-11230
=> fix: update documentation URLs (v36)

src/components/page-helper/PageHelper.js, src/helpers/docs.js
Closes https://jira.dhis2.org/browse/DHIS2-11230
=> fix: update documentation URLs (v34)

src/grid.css
v36 backport of https://github.com/dhis2/data-quality-app/pull/779
=> fix: add missing column styles to grid.css (v36)

src/pages/follow-up-analysis/Form.js, src/pages/outlier-detection/Form.js, src/pages/validation-rules-analysis/Form.js
v36 backport of https://github.com/dhis2/data-quality-app/pull/781
=> fix: return error messages when showing critical alerts (v36)

package.json, yarn.lock
Backport of #793 
Fixes a service worker issue: https://jira.dhis2.org/browse/DHIS2-11487
=> fix: bump cli-app-scripts to 7.1.0 (v36)

i18n/en.pot, src/pages/OutlierDetection/Form/Form.js, src/pages/OutlierDetection/Form/ZScoreFields.js, src/pages/OutlierDetection/OutlierAnalysisTable/ElementRow.js, src/pages/OutlierDetection/OutlierAnalysisTable/OutlierAnalysisTable.js, src/pages/OutlierDetection/OutlierDetection.js, src/pages/OutlierDetection/constants.js
Add support for outlier detection: https://jira.dhis2.org/browse/DHIS2-11663
Did some minor refactoring to integrate this change.
=> feat(outlier-detection): support for modified z-score

src/pages/FollowUpAnalysis/FollowUpAnalysis.js, src/pages/OutlierDetection/OutlierDetection.js, src/pages/ValidationRulesAnalysis/ValidationRulesAnalysis.js
Backport of https://github.com/dhis2/data-quality-app/pull/1014
fixes [BETA-28](https://dhis2.atlassian.net/browse/BETA-28)
[BETA-28]: https://dhis2.atlassian.net/browse/BETA-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: disable button if start date is after end date (patch/2.40.0)

src/pages/FollowUpAnalysis/FollowUpAnalysis.js, src/pages/OutlierDetection/OutlierDetection.js, src/pages/ValidationRulesAnalysis/ValidationRulesAnalysis.js
Backport of https://github.com/dhis2/data-quality-app/pull/1014
fixes [BETA-28](https://dhis2.atlassian.net/browse/BETA-28)
[BETA-28]: https://dhis2.atlassian.net/browse/BETA-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: disable button if start date is after end date (v40)

src/components/FormattedNumber/FormattedNumber.js
Addresses [DHIS2-10825](https://dhis2.atlassian.net/browse/DHIS2-10825)
Recommended parameters on the Sierra Leone demo, since getting a good sample can be weird:
1. Follow-up analysis:
a. Data set = Child Health
b. Parent org unit = Sierra Leone
c. Dates = 2023-06-01 to 2023-09-30 (three months)
3. Validation rule analysis:
a. Parent org unit = Sierra Leone
b. Dates = 2023-06-01 to 2023-06-30 (one month)
c. Validation rule group = ANC
Before:
---
After:
[DHIS2-10825]: https://dhis2.atlassian.net/browse/DHIS2-10825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: trailing zeroes [DHIS2-10825]

src/components/FormattedNumber/FormattedNumber.js
=> fix: trailing zeroes (v38) [DHIS2-10825]

src/components/FormattedNumber/FormattedNumber.js
=> fix: trailing zeroes (v39) [DHIS2-10825]

src/components/FormattedNumber/FormattedNumber.js
Backport of https://github.com/dhis2/data-quality-app/pull/1129
=> fix: trailing zeroes (v40) [DHIS2-10825]
